spring.application.name=park-api

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# DATABASE CONFIGURATION POSTGRESQL
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_park
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA CONFIGURATION
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update