services:
  postgres:
    image: postgres:17
    container_name: postgresPark
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: demo_park
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: